packaging_format = 2

id = "seaweedfs"
name = "SeaweedFS"
description.en = "SeaweedFS is a versatile and efficient storage system"
description.fr = "SeaweedFS is a versatile and efficient storage system"

version = "4.07~ynh1"

maintainers = [""]

[upstream]
license = "Apache License 2.0" # you can see the available licenses identifiers list here: https://spdx.org/licenses/
website = "https://seaweedfs.com/"
userdoc = "https://github.com/seaweedfs/seaweedfs/wiki"
code = "https://github.com/seaweedfs/seaweedfs"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ['amd64']
multi_instance = false

ldap = false
sso = false

disk = "200M"
ram.build = "200M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"
   
[resources]
    [resources.sources.main]

   url = "https://github.com/seaweedfs/seaweedfs/releases/download/4.07/linux_amd64.tar.gz"
   sha256 = "61c8a132c6753cc6726ab6dcc761e0fb2ae2bf7310b1276e82427f4a33dc2a7b"       
   autoupdate.strategy = "latest_github_tag"
   in_subdir = false
   

   
    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["datadir"]

    [resources.permissions]

    main.url = "/"
    admin.url = "/admin"
    admin.allowed = "admins"
    admin.auth_header = false
    
    [resources.ports]
    admin.default = 23646
    master.default = 9333
    filer.default = 8888
    volume.default = 8080
    api.default = 8333 # port pour s3
    
